ColegioWebApplication/src/java/com/interrapidisimo/model/entities/Persona.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interrapidisimo.model.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Henry
 */
@Entity
@Table(name = "persona")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Persona.findAll", query = "SELECT p FROM Persona p"),
    @NamedQuery(name = "Persona.findByPersonaId", query = "SELECT p FROM Persona p WHERE p.personaId = :personaId"),
    @NamedQuery(name = "Persona.findByPersonaNombre", query = "SELECT p FROM Persona p WHERE p.personaNombre = :personaNombre"),
    @NamedQuery(name = "Persona.findByPersonaApellido", query = "SELECT p FROM Persona p WHERE p.personaApellido = :personaApellido"),
    @NamedQuery(name = "Persona.findByPersonaTelefono", query = "SELECT p FROM Persona p WHERE p.personaTelefono = :personaTelefono"),
    @NamedQuery(name = "Persona.findByPersonaDocumento", query = "SELECT p FROM Persona p WHERE p.personaDocumento = :personaDocumento")})
public class Persona implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "persona_id")
    private Integer personaId;
    @Size(max = 120)
    @Column(name = "persona_nombre")
    private String personaNombre;
    @Size(max = 120)
    @Column(name = "persona_apellido")
    private String personaApellido;
    @Size(max = 12)
    @Column(name = "persona_telefono")
    private String personaTelefono;
    @Size(max = 30)
    @Column(name = "persona_documento")
    private String personaDocumento;
    @JoinColumn(name = "TipoDocumnto_tipodocumnto_id", referencedColumnName = "tipodocumnto_id")
    @ManyToOne(optional = false)
    private Tipodocumnto tipoDocumntotipodocumntoid;
    @JoinColumn(name = "TipoPersona_tipopersona_id", referencedColumnName = "tipopersona_id")
    @ManyToOne(optional = false)
    private Tipopersona tipoPersonatipopersonaid;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "personapersonaid")
    private Collection<Personamateria> personamateriaCollection;

    public Persona() {
    }

    public Persona(Integer personaId) {
        this.personaId = personaId;
    }

    public Integer getPersonaId() {
        return personaId;
    }

    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }

    public String getPersonaNombre() {
        return personaNombre;
    }

    public void setPersonaNombre(String personaNombre) {
        this.personaNombre = personaNombre;
    }

    public String getPersonaApellido() {
        return personaApellido;
    }

    public void setPersonaApellido(String personaApellido) {
        this.personaApellido = personaApellido;
    }

    public String getPersonaTelefono() {
        return personaTelefono;
    }

    public void setPersonaTelefono(String personaTelefono) {
        this.personaTelefono = personaTelefono;
    }

    public String getPersonaDocumento() {
        return personaDocumento;
    }

    public void setPersonaDocumento(String personaDocumento) {
        this.personaDocumento = personaDocumento;
    }

    public Tipodocumnto getTipoDocumntotipodocumntoid() {
        return tipoDocumntotipodocumntoid;
    }

    public void setTipoDocumntotipodocumntoid(Tipodocumnto tipoDocumntotipodocumntoid) {
        this.tipoDocumntotipodocumntoid = tipoDocumntotipodocumntoid;
    }

    public Tipopersona getTipoPersonatipopersonaid() {
        return tipoPersonatipopersonaid;
    }

    public void setTipoPersonatipopersonaid(Tipopersona tipoPersonatipopersonaid) {
        this.tipoPersonatipopersonaid = tipoPersonatipopersonaid;
    }

    @XmlTransient
    public Collection<Personamateria> getPersonamateriaCollection() {
        return personamateriaCollection;
    }

    public void setPersonamateriaCollection(Collection<Personamateria> personamateriaCollection) {
        this.personamateriaCollection = personamateriaCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (personaId != null ? personaId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Persona)) {
            return false;
        }
        Persona other = (Persona) object;
        if ((this.personaId == null && other.personaId != null) || (this.personaId != null && !this.personaId.equals(other.personaId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Rol: "+tipoPersonatipopersonaid.getTipopersonaNombre()+" Nombre: "+personaNombre+" "+personaApellido ;
    }
    
}

ColegioWebApplication/src/java/com/interrapidisimo/controller/managedbean/PersonaController.java
package com.interrapidisimo.controller.managedbean;

import com.interrapidisimo.model.entities.Persona;
import com.interrapidisimo.controller.managedbean.util.JsfUtil;
import com.interrapidisimo.controller.managedbean.util.JsfUtil.PersistAction;
import com.interrapidisimo.model.facade.PersonaFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("personaController")
@SessionScoped
public class PersonaController implements Serializable {

    @EJB
    private com.interrapidisimo.model.facade.PersonaFacade ejbFacade;
    private List<Persona> items = null;
    private Persona selected;

    public PersonaController() {
    }

    public Persona getSelected() {
        return selected;
    }

    public void setSelected(Persona selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PersonaFacade getFacade() {
        return ejbFacade;
    }

    public Persona prepareCreate() {
        selected = new Persona();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("PersonaCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("PersonaUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("PersonaDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Persona> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Persona getPersona(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Persona> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Persona> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Persona.class)
    public static class PersonaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PersonaController controller = (PersonaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "personaController");
            return controller.getPersona(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Persona) {
                Persona o = (Persona) object;
                return getStringKey(o.getPersonaId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Persona.class.getName()});
                return null;
            }
        }

    }

}

ColegioWebApplication/web/persona/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonaCreateDlg" widgetVar="PersonaCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePersonaTitle}">
            <h:form id="PersonaCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personaController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_personaNombre}" for="personaNombre" />
                        <p:inputText id="personaNombre" value="#{personaController.selected.personaNombre}" title="#{bundle.CreatePersonaTitle_personaNombre}" />
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_personaApellido}" for="personaApellido" />
                        <p:inputText id="personaApellido" value="#{personaController.selected.personaApellido}" title="#{bundle.CreatePersonaTitle_personaApellido}" />
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_personaTelefono}" for="personaTelefono" />
                        <p:inputText id="personaTelefono" value="#{personaController.selected.personaTelefono}" title="#{bundle.CreatePersonaTitle_personaTelefono}" />
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_personaDocumento}" for="personaDocumento" />
                        <p:inputText id="personaDocumento" value="#{personaController.selected.personaDocumento}" title="#{bundle.CreatePersonaTitle_personaDocumento}" />
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_tipoDocumntotipodocumntoid}" for="tipoDocumntotipodocumntoid" />
                        <p:selectOneMenu id="tipoDocumntotipodocumntoid" value="#{personaController.selected.tipoDocumntotipodocumntoid}" required="true" requiredMessage="#{bundle.EditPersonaRequiredMessage_tipoDocumntotipodocumntoid}">
                            <f:selectItems value="#{tipodocumntoController.itemsAvailableSelectOne}"
                                           var="tipoDocumntotipodocumntoidItem"
                                           itemValue="#{tipoDocumntotipodocumntoidItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePersonaLabel_tipoPersonatipopersonaid}" for="tipoPersonatipopersonaid" />
                        <p:selectOneMenu id="tipoPersonatipopersonaid" value="#{personaController.selected.tipoPersonatipopersonaid}" required="true" requiredMessage="#{bundle.EditPersonaRequiredMessage_tipoPersonatipopersonaid}">
                            <f:selectItems value="#{tipopersonaController.itemsAvailableSelectOne}"
                                           var="tipoPersonatipopersonaidItem"
                                           itemValue="#{tipoPersonatipopersonaidItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{personaController.create}" value="#{bundle.Save}" update="display,:PersonaListForm:datalist,:growl" oncomplete="handleSubmit(args,'PersonaCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PersonaCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

ColegioWebApplication/web/persona/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonaEditDlg" widgetVar="PersonaEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPersonaTitle}">
            <h:form id="PersonaEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personaController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPersonaLabel_personaNombre}" for="personaNombre" />
                        <p:inputText id="personaNombre" value="#{personaController.selected.personaNombre}" title="#{bundle.EditPersonaTitle_personaNombre}" />
                        <p:outputLabel value="#{bundle.EditPersonaLabel_personaApellido}" for="personaApellido" />
                        <p:inputText id="personaApellido" value="#{personaController.selected.personaApellido}" title="#{bundle.EditPersonaTitle_personaApellido}" />
                        <p:outputLabel value="#{bundle.EditPersonaLabel_personaTelefono}" for="personaTelefono" />
                        <p:inputText id="personaTelefono" value="#{personaController.selected.personaTelefono}" title="#{bundle.EditPersonaTitle_personaTelefono}" />
                        <p:outputLabel value="#{bundle.EditPersonaLabel_personaDocumento}" for="personaDocumento" />
                        <p:inputText id="personaDocumento" value="#{personaController.selected.personaDocumento}" title="#{bundle.EditPersonaTitle_personaDocumento}" />
                        <p:outputLabel value="#{bundle.EditPersonaLabel_tipoDocumntotipodocumntoid}" for="tipoDocumntotipodocumntoid" />
                        <p:selectOneMenu id="tipoDocumntotipodocumntoid" value="#{personaController.selected.tipoDocumntotipodocumntoid}" required="true" requiredMessage="#{bundle.EditPersonaRequiredMessage_tipoDocumntotipodocumntoid}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipodocumntoController.itemsAvailableSelectOne}"
                                           var="tipoDocumntotipodocumntoidItem"
                                           itemValue="#{tipoDocumntotipodocumntoidItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditPersonaLabel_tipoPersonatipopersonaid}" for="tipoPersonatipopersonaid" />
                        <p:selectOneMenu id="tipoPersonatipopersonaid" value="#{personaController.selected.tipoPersonatipopersonaid}" required="true" requiredMessage="#{bundle.EditPersonaRequiredMessage_tipoPersonatipopersonaid}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipopersonaController.itemsAvailableSelectOne}"
                                           var="tipoPersonatipopersonaidItem"
                                           itemValue="#{tipoPersonatipopersonaidItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{personaController.update}" value="#{bundle.Save}" update="display,:PersonaListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PersonaEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PersonaEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

ColegioWebApplication/web/persona/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPersonaTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="PersonaListForm">
                <p:panel header="#{bundle.ListPersonaTitle}">
                    <p:dataTable id="datalist" value="#{personaController.items}" var="item"
                                 selectionMode="single" selection="#{personaController.selected}"
                                 paginator="true"
                                 rowKey="#{item.personaId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_personaId}"/>
                            </f:facet>
                            <h:outputText value="#{item.personaId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_personaNombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.personaNombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_personaApellido}"/>
                            </f:facet>
                            <h:outputText value="#{item.personaApellido}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_personaTelefono}"/>
                            </f:facet>
                            <h:outputText value="#{item.personaTelefono}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_personaDocumento}"/>
                            </f:facet>
                            <h:outputText value="#{item.personaDocumento}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_tipoDocumntotipodocumntoid}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipoDocumntotipodocumntoid.tipodocumntoNombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPersonaTitle_tipoPersonatipopersonaid}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipoPersonatipopersonaid.tipopersonaNombre}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{personaController.prepareCreate}" update=":PersonaCreateForm" oncomplete="PF('PersonaCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PersonaViewForm" oncomplete="PF('PersonaViewDialog').show()" disabled="#{empty personaController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PersonaEditForm" oncomplete="PF('PersonaEditDialog').show()" disabled="#{empty personaController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{personaController.destroy}" update=":growl,datalist" disabled="#{empty personaController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

ColegioWebApplication/web/persona/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PersonaViewDlg" widgetVar="PersonaViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPersonaTitle}">
            <h:form id="PersonaViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{personaController.selected != null}">
                        <h:outputText value="#{bundle.ViewPersonaLabel_personaId}"/>
                        <h:outputText value="#{personaController.selected.personaId}" title="#{bundle.ViewPersonaTitle_personaId}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_personaNombre}"/>
                        <h:outputText value="#{personaController.selected.personaNombre}" title="#{bundle.ViewPersonaTitle_personaNombre}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_personaApellido}"/>
                        <h:outputText value="#{personaController.selected.personaApellido}" title="#{bundle.ViewPersonaTitle_personaApellido}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_personaTelefono}"/>
                        <h:outputText value="#{personaController.selected.personaTelefono}" title="#{bundle.ViewPersonaTitle_personaTelefono}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_personaDocumento}"/>
                        <h:outputText value="#{personaController.selected.personaDocumento}" title="#{bundle.ViewPersonaTitle_personaDocumento}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_tipoDocumntotipodocumntoid}"/>
                        <h:outputText value="#{personaController.selected.tipoDocumntotipodocumntoid.tipodocumntoNombre}" title="#{bundle.ViewPersonaTitle_tipoDocumntotipodocumntoid}"/>
                        <h:outputText value="#{bundle.ViewPersonaLabel_tipoPersonatipopersonaid}"/>
                        <h:outputText value="#{personaController.selected.tipoPersonatipopersonaid.tipopersonaNombre}" title="#{bundle.ViewPersonaTitle_tipoPersonatipopersonaid}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PersonaViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>