vacaciones/src/main/java/net/amantium/vacaciones/controlador/managedbean/FestivoMB.java
package net.amantium.vacaciones.controlador.managedbean;

import org.springframework.beans.factory.annotation.Autowired;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import net.amantium.vacaciones.modelo.entidad.Festivo;
import net.amantium.vacaciones.modelo.servicio.FestivoService;

@Named
@ViewScoped
public class FestivoMB implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Autowired
	private FestivoService festivoService;
	
	private Festivo festivo;
	

	@PostConstruct
	public void init() {
		setFestivo(new Festivo());
	}

	public Festivo getFestivo() {
		return festivo;
	}


	public void setFestivo(Festivo festivo) {
		this.festivo = festivo;
	}





	public List<Festivo> getListEstado() {
		return festivoService.getListEstado();
	}
	
	public String guardar()
	{
		
		festivoService.setGuardarEstado(getFestivo());
		setFestivo(new Festivo());
		return "/festivo/listFestivo.xhtml?faces-redirect=true";
	}

	public String preparoActualizar(Integer id)
	{
		setFestivo(festivoService.getEstado(id));
		return "/festivo/editFestivo.xhtml?faces-redirect=true";
	}
	public String actualizar()
	{
		festivoService.setGuardarEstado(getFestivo());
		setFestivo (new Festivo());
		return "/festivo/listFestivo.xhtml?faces-redirect=true";
	}
	
	public String elminimar(Integer id)
	{
		festivoService.setEliminarEstado(id);
		return "/festivo/index.xhtml?faces-redirect=true";
	}

	
}

vacaciones/src/main/webapp/festivo/createFestivo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Form</title>
	<h:outputStylesheet name="/css/bootstrap.min.css" />
</h:head>
<h:body>
	<style type="text/css">
.ui-panelgrid.showcase-text-align-center .ui-grid-responsive .ui-panelgrid-cell
	{
	text-align: center;
}

.customPanelGrid .ui-panelgrid-content {
	align-items: center;
}
</style>
	<h:form>
		<p:panelGrid columns="2"
			columnClasses="ui-grid-col-2,ui-grid-col-4,ui-grid-col-2,ui-grid-col-4"
			layout="grid" styleClass="ui-panelgrid-blank ui-fluid"
			style="border:0px none; background-color:transparent;">

			<p:row styleClass="my-heading-row" style="font-weight: bold">
			Crear
            </p:row>

			<p:outputLabel></p:outputLabel>

			<p:outputLabel for="fecha">Fecha Festivo</p:outputLabel>
			<p:datePicker id="fecha" value="#{festivoMB.festivo.fecha}"
				required="true" />
			<p:outputLabel for="dias">Nombre</p:outputLabel>
			<p:inputText id="dias" value="#{festivoMB.festivo.nombre}"
				required="true" />
			<p:outputLabel for="desc">Descripción</p:outputLabel>
			<p:inputText id="desc" value="#{festivoMB.festivo.descripcion}"
				required="true"></p:inputText>

			<p:row>
				<p:commandButton update="@form" value="Save"
					action="#{festivoMB.guardar()}" style="width: auto">
				</p:commandButton>
				<p:commandButton value="Back" style="width: auto" />
			</p:row>


		</p:panelGrid>
	</h:form>
</h:body>
</html>

vacaciones/src/main/webapp/festivo/editFestivo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Form</title>
	<h:outputStylesheet name="/css/bootstrap.min.css" />
</h:head>
<h:body>
	<style type="text/css">
.ui-panelgrid.showcase-text-align-center .ui-grid-responsive .ui-panelgrid-cell
	{
	text-align: center;
}

.customPanelGrid .ui-panelgrid-content {
	align-items: center;
}
</style>
	<h:form>
		<p:panelGrid columns="2"
			columnClasses="ui-grid-col-2,ui-grid-col-4,ui-grid-col-2,ui-grid-col-4"
			layout="grid" styleClass="ui-panelgrid-blank ui-fluid"
			style="border:0px none; background-color:transparent;">

			<p:row styleClass="my-heading-row" style="font-weight: bold">
			Crear
            </p:row>

			<p:outputLabel></p:outputLabel>

			<p:outputLabel for="fecha">Fecha Festivo</p:outputLabel>
			<p:datePicker id="fecha" value="#{festivoMB.festivo.fecha}"
				required="true" />
			<p:outputLabel for="dias">Nombre</p:outputLabel>
			<p:inputText id="dias" value="#{festivoMB.festivo.nombre}"
				required="true" />
			<p:outputLabel for="desc">Descripción</p:outputLabel>
			<p:inputText id="desc" value="#{festivoMB.festivo.descripcion}"
				required="true"></p:inputText>

			<p:row>
				<p:commandButton update="@form" value="Save"
					action="#{festivoMB.actualizar()}" style="width: auto">
				</p:commandButton>
				<p:commandButton value="Back" style="width: auto" />
			</p:row>


		</p:panelGrid>
	</h:form>
</h:body>
</html>

vacaciones/src/main/webapp/festivo/listFestivo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
	<title>User Details</title>
	<h:outputStylesheet name="/css/bootstrap.min.css" />

</h:head>
<h:body>
	
			<h:form>
				<div class="ui-fluid">
					<center>
						<h2>
							<h:outputLabel name="title">Solicitud Vacaciones</h:outputLabel>
						</h2>
					</center>
				</div>
				<br />
				<div class="p-field">

					<p:commandButton
						action="/festivo/createFestivo.xhtml?faces-redirect=true"
						value="Create New User" class="btn btn-success"></p:commandButton>


				</div>
				<br />
				<div class="p-field">
					<p:dataTable binding="#{table}"
						value="#{festivoMB.listEstado}" var="u">
						
						<p:column>
							<f:facet name="header">Nombre</f:facet>
							<h:outputText value="#{u.nombre}" />
						</p:column>
						<p:column>
							<f:facet name="header">Fecha </f:facet>
							<h:outputText value="#{u.fecha}" />
						</p:column>
						<p:column>
							<f:facet name="header">Descripción</f:facet>
							<h:outputText value="#{u.descripcion}" />
						</p:column>
												<p:column>
							<f:facet name="header"></f:facet>
							<p:commandButton
								action="#{festivoMB.preparoActualizar(u.id)}"
								value="Actualizar">
							</p:commandButton>
							<p:commandButton action="#{festivoMB.elminimar(u.id)}"
								value="Eliminar">
							</p:commandButton>
						</p:column>
					</p:dataTable>
				</div>
			</h:form>
</h:body>
</html>